version: '3'

services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    env_file:
      - .env
    #volumes:
    #  - ${PWD}/db-data/:/var/lib/postgresql/data/
    #  - ${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  #pgadmin:
  #  image: dpage/pgadmin4
  #  ports:
  #    - 15433:80
  #  env_file:
  #    - .env
  #  depends_on:
  #    - database
  #  volumes:
  #    - ${PWD}/pgadmin-data/:/var/lib/pgadmin/