---
version: '3'
services:

  actix-api:
    build: ../web-apis/actix-api/docker/
    # image: docker.io/nierhoff/rust-playground/actix-api
    platform: linux/arm64/v8
    hostname: actix-api
    container_name: actix-api
    ports:
      - "8081:8080"
