[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build]
command = "wasm-pack"
args = ["build", "--target", "web"]
dependencies = ["clean"]

[tasks.test]
command = "wasm-pack"
args = ["test", "--chrome", "--headless"]
dependencies = ["build"]

[tasks.docker-copy]
script_runner = "@duckscript"
script = '''
rm -r ${CARGO_MAKE_WORKING_DIRECTORY}/docker/target/
cp ${CARGO_MAKE_WORKING_DIRECTORY}/pkg ${CARGO_MAKE_WORKING_DIRECTORY}/docker/target/
'''

[tasks.docker-copy2]
script_runner = "@duckscript"
script = '''
rm -r ${CARGO_MAKE_WORKING_DIRECTORY}/docker/target/public
cp ${CARGO_MAKE_WORKING_DIRECTORY}/../public ${CARGO_MAKE_WORKING_DIRECTORY}/docker/target/public
'''

[tasks.docker-build]
disabled = false
dependencies = ["docker-prepare", "docker-copy", "docker-copy2"]

[tasks.myci]
dependencies = [
    "format",
    "build",
    "test",
    "docker-build"
]
